"""
统一定义摔倒检测事件在 YOLO、VLM、人工复核、隐私保护、完整性校验和归档流程中的状态字符串，供后续模块复用，避免不同文件里手写状态值导致拼写不一致。
"""

YOLO_CANDIDATE = "yolo_candidate"

VLM_PENDING = "vlm_pending"
VLM_PROCESSING = "vlm_processing"
VLM_FAILED = "vlm_failed"

CONFIRMED_FALL = "confirmed_fall"
REJECTED = "rejected"
NEED_HUMAN_REVIEW = "need_human_review"

PRIVACY_PENDING = "privacy_pending"
INTEGRITY_PENDING = "integrity_pending"
RETENTION_PENDING = "retention_pending"
ARCHIVED = "archived"

VLM_JOB_EVENT_STATUSES = (
    VLM_PENDING,
    VLM_PROCESSING,
    VLM_FAILED,
)

FINAL_DETECTION_STATUSES = (
    CONFIRMED_FALL,
    REJECTED,
    NEED_HUMAN_REVIEW,
)

DOWNSTREAM_PENDING_STATUSES = (
    PRIVACY_PENDING,
    INTEGRITY_PENDING,
    RETENTION_PENDING,
)

TERMINAL_EVENT_STATUSES = (
    REJECTED,
    NEED_HUMAN_REVIEW,
    ARCHIVED,
)

ALL_EVENT_STATUSES = (
    YOLO_CANDIDATE,
    VLM_PENDING,
    VLM_PROCESSING,
    CONFIRMED_FALL,
    REJECTED,
    NEED_HUMAN_REVIEW,
    VLM_FAILED,
    PRIVACY_PENDING,
    INTEGRITY_PENDING,
    RETENTION_PENDING,
    ARCHIVED,
)

__all__ = [
    "YOLO_CANDIDATE",
    "VLM_PENDING",
    "VLM_PROCESSING",
    "VLM_FAILED",
    "CONFIRMED_FALL",
    "REJECTED",
    "NEED_HUMAN_REVIEW",
    "PRIVACY_PENDING",
    "INTEGRITY_PENDING",
    "RETENTION_PENDING",
    "ARCHIVED",
    "VLM_JOB_EVENT_STATUSES",
    "FINAL_DETECTION_STATUSES",
    "DOWNSTREAM_PENDING_STATUSES",
    "TERMINAL_EVENT_STATUSES",
    "ALL_EVENT_STATUSES",
]
